{% set name = "album" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56cabcd054a3f4f1c4665964a4efc76144e9b12f90b4e78874ee38a6831b94d3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - album=album.__main__:startup
    - album-catalog-admin=album.ci.__main__:startup

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pip
    - python >={{ python_min }}
    - {{ pin_compatible('album-solution-api', lower_bound='0.7.0', upper_bound='0.8.0') }}
    - {{ pin_compatible('album-environments', lower_bound='0.3.0', upper_bound='0.4.0') }}
    - pyyaml >=6.0
    - validators >=0.18.2
    - git >=2.37
    - gitpython >=3.1.13
    - requests >=2.28
    - pexpect >=4.8.0
    - jsonschema >=4.0.0
    - colorlog >=6.6.0
    - pywin32-on-windows >=0.1.0
    - packaging >=21.3
    - pre-commit >=2.20.0
    - pooch >=1.4.0

test:
  imports:
    - album
  commands:
    - pip list
    - pip check
    - album --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://album.solutions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Album is a framework for unifying computational tools across frameworks, languages, and environments.
  doc_url: https://docs.album.solutions
  dev_url: https://gitlab.com/album-app/album

extra:
  recipe-maintainers:
    - jpalbrecht
    - frauzufall
